name: "Coverage Report"

on:
  pull_request:
  push:
    branches:
    tags:

jobs:
  run-tests:
    name: PHPUnit on ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2']

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4.1.3

      - name: "Setup PHP"
        uses: shivammathur/setup-php@2.30.4
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.php_extensions }}
          coverage: pcov
          ini-values: pcov.enabled=1

      - uses: "ramsey/composer-install@3.0.0"
        with:
          composer-options: "${{ matrix.composer-options }}"

      - name: "Run Tests"
        run: php ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: "Upload Coverage to CodeCov"
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
